"""added borrow book time in borrow book model

Revision ID: 4260aef17089
Revises: 45d4bd9ef2b9
Create Date: 2024-03-04 10:07:29.217532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4260aef17089'
down_revision = '45d4bd9ef2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrow_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_book', schema=None) as batch_op:
        batch_op.drop_column('borrow_date')

    # ### end Alembic commands ###
