"""added borrow book model

Revision ID: 45d4bd9ef2b9
Revises: 6334253858e7
Create Date: 2024-02-02 22:52:44.406979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d4bd9ef2b9'
down_revision = '6334253858e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_name'], ['books.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    op.drop_table('borrow_book')
    # ### end Alembic commands ###
